### ISSUE TITLE
Make a cool feature image for upcoming Communia episode

### ISSUE THREAD

**Issue by aariops** [WhiteMarketPodcast/whitemarketpodcast-repo#1]
On the next [WMP](https://www.whitemarketpodcast.co.uk/) episode, we will be featuring [Communia](https://www.communia-association.org/). We need a cool picture to go with it. 

Specs:
- 1920x1080 (full HD)
- *.png or *.jpg
- should look good when cropped to a square (center focused)
- should only use works under public domain, [CC 0](https://creativecommons.org/share-your-work/public-domain/cc0/), CC BY or CC BY-SA. You can find out more about these licences [here](https://creativecommons.org/share-your-work/licensing-types-examples/)
- should feature Communia's logo ( https://pbs.twimg.com/media/DM6YZFEW0AEvmn5.jpg:large)

**Comment by juanluischaurant** [comment]
Awesome, I got this one!

**Comment by aariops** [comment]
Fixed on issue #2
