### ISSUE TITLE
I got the image

### ISSUE THREAD

**Issue by juanluischaurant** [WhiteMarketPodcast/whitemarketpodcast-repo#2]
The image is ready, trying to make the pull request

**Comment by aariops** [comment]
hey Juan! Welcome to the team! thank you so much :1st_place_medal: 

 I don't think github allows upload of images and I am still adding guidelines for things like that (sorry). Can you host it on Archive.org / Dropbox (and something similar) and link it?

**Comment by juanluischaurant** [comment]
Perfect, give me a few minutes, thanks a lot.

**Comment by aariops** [comment]
Since hacktoberfest works on a pull-request system, maybe you can submit your link on an *.md or *.txt file, so you can get all the credit you deserve.

**Comment by acabunoc** [comment]
@juanluischaurant I was able to make a PR with an image here: https://github.com/WhiteMarketPodcast/whitemarketpodcast-repo/pull/3

Hope this helps!

**Comment by juanluischaurant** [comment]
Here is the link for my image:
https://archive.org/details/communia

I was thinking about an *.md file as well, but my internet does not allows me to operate faster.
Thanks @acabunoc I am checking it out.

**Comment by aariops** [comment]
Thank you so much for your help @juanluischaurant. The image looks really cool. I'll make sure to credit you when the episode is out. 
and thank you @acabunoc for the technical help :smile:

**Comment by juanluischaurant** [comment]
Awesome!
And also, would  be nice to contribute again in the future, I like the mission of the project.
