### ISSUE TITLE
Have you been at MozFest? Send an audio clip for episode 4.04

### ISSUE THREAD

**Issue by aariops** [WhiteMarketPodcast/whitemarketpodcast-repo#6]
Hi,

We're preparing episode 4.04, which will be about MozFest. If you were at MozFest, send us an audio clip sharing your experience to whitemarketpodcast [at] gmail.com . 

- If you were a facilitator, how did your session go? 
- What was your favourite session?
- What did you like the most? 
- Who was your favourite new contact? 
- What topic/view really made you rethink your work? 
- Etc, etc, etc. Anything that you'd like to share about your experience :)

You can send mp3, wav, m4a, flac or ogg. If your file is >15MB, please send a Dropbox/WeTransfer link (or some other link alike).  

If you are really shy, you can just hit me up with an email.

Please include your name (alias) and project (if you'd like me to mention it).

**This issue will be open until November 30th.**

Cheers

**Comment by ryanwarsaw** [comment]
Sounds interesting, I'd love to help out. Will need to wait for some quiet space where there isn't a lot of obnoxious background noise!

**Comment by aariops** [comment]
hey @ryanwarsaw! sound quality doesn't have to be perfect. I look forward to receive your contribution 😄

**Comment by rainsworth** [comment]
I will get you a recording by 30 Nov! 📻 🎙 🦊
